### PR TITLE
Add CI tests for Python 3.5

### PR DESCRIPTION
**Pull request by zoidyzoidzoid**

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by adrianmoisey** [comment]
You seem to be ahead of the curve

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by adrianmoisey** [comment]
:+1:

**Comment by zoidyzoidzoid** [comment]
@zoidbergwill: you should've added the Python 3.5 classifier while you were here, dummy.

**Pull request merged**
