### PR TITLE
Make initial Ticket params configurable.

### PR DESCRIPTION
**Pull request by ekoval**
Make initial Ticket params configurable.

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by ekoval** [comment]
ping @stefanor @RayeN

**Comment by ekoval** [comment]
This is far from perfect, I'd like to be able to pass this as a param of Ticket.create(), but still better than what we have now.

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by RayeN** [comment]
:+1: Looks good to me.

**Comment by stefanor** [comment]
:+1: from here too

**Pull request merged**
